# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mfb2 blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blogging site for mfb2.
baseurl: "" # the subpath of your site, e.g. /blog
url: 
twitter_username: mfrb2
github_username:  mfb2

# Build settings
markdown: kramdown
